const APP_ACTIONS = {
  DISPLAY_LOADER: 'DISPLAY_LOADER',
  HIDE_LOADER: 'HIDE_LOADER',

  ADD_PRODUCTS: 'ADD_PRODUCTS',
  APPEND_PRODUCTS: 'APPEND_PRODUCTS',
  ADD_PRODUCT: 'ADD_PRODUCT',

  ADD_ORDERS: 'ADD_ORDERS',
  ADD_ORDER: 'ADD_ORDER',

  ADD_TAXONS: 'ADD_TAXONS',

  CREATE_ORDER: 'CREATE_ORDER',
  ADD_PRODUCT_TO_CART: 'ADD_PRODUCT_TO_CART',
  DESTROY_ORDER: 'DESTROY_ORDER',
  REMOVE_LINE_ITEM: 'REMOVE_LINE_ITEM',
  UPDATE_LINE_ITEM: 'UPDATE_LINE_ITEM',

  SET_FLASH: 'SET_FLASH',
  HIDE_FLASH: 'HIDE_FLASH',

  ADD_COUNTRIES: 'ADD_COUNTRIES',

  SET_CURRENT_CHECKOUT_STEP: 'SET_CURRENT_CHECKOUT_STEP',
  CLEAR_CURRENT_CHECKOUT_STEP: 'CLEAR_CURRENT_CHECKOUT_STEP'
};

export default APP_ACTIONS;
