const APP_ACTIONS = {
  DISPLAY_LOADER: 'DISPLAY_LOADER',
  HIDE_LOADER: 'HIDE_LOADER',
  ADD_PRODUCTS: 'ADD_PRODUCTS',
  ADD_PRODUCT: 'ADD_PRODUCT',
  ADD_TAXONS: 'ADD_TAXONS',

  CREATE_ORDER: 'CREATE_ORDER',
  ADD_PRODUCT_TO_CART: 'ADD_PRODUCT_TO_CART',
  REMOVE_LINE_ITEM: 'REMOVE_LINE_ITEM',
  UPDATE_LINE_ITEM: 'UPDATE_LINE_ITEM',
  SET_FLASH: 'SET_FLASH',
  HIDE_FLASH: 'HIDE_FLASH'
};

export default APP_ACTIONS;
